# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-18 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeIntervals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(max_length=20)),
                ('end_time', models.CharField(max_length=20)),
                ('con_id', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='continent',
            name='file',
            field=models.ImageField(upload_to=b'', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='continent',
            name='toppings',
            field=models.ManyToManyField(to='app.TimeIntervals'),
        ),
    ]
