# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-28 03:59
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161127_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='my_field',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(b'item_key1', b'Item title 1.1'), (b'item_key2', b'Item title 1.2'), (b'item_key3', b'Item title 1.3'), (b'item_key4', b'Item title 1.4'), (b'item_key5', b'Item title 1.5')], default='', max_length=49),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ads',
            name='my_field2',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, b'Item title 2.1'), (2, b'Item title 2.2'), (3, b'Item title 2.3'), (4, b'Item title 2.4'), (5, b'Item title 2.5')], default='', max_length=3),
            preserve_default=False,
        ),
    ]
