# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-28 07:29
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20161128_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='my_field2',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, b'\xe5\xa4\xa7\xe5\x9b\xbe\xe5\xb9\xbf\xe5\x91\x8a'), (2, b'\xe9\xa6\x96\xe9\xa1\xb5banner'), (3, b'\xe7\x89\xb9\xe6\x83\xa0banner'), (4, b'\xe5\x8f\xb3\xe6\x8b\x89banner'), (5, b'\xe5\x88\x97\xe8\xa1\xa8\xe9\xa1\xb5')], max_length=10),
        ),
    ]
