# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-01 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20161128_0729'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZUser',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('pnum', models.BigIntegerField(unique=True)),
                ('pnum_md5', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('status', models.IntegerField()),
                ('device_id', models.CharField(max_length=50, unique=True)),
                ('imsi', models.CharField(max_length=50)),
                ('os_type', models.CharField(max_length=50)),
                ('ctime', models.DateTimeField()),
                ('register_ip', models.CharField(max_length=15)),
                ('invite_code', models.IntegerField()),
                ('channel', models.CharField(blank=True, max_length=15, null=True)),
                ('ulevel', models.IntegerField()),
                ('from_app', models.IntegerField()),
                ('update_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'z_user',
                'managed': False,
            },
        ),
    ]
